import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext(null);

const translations = {
  hu: {
    // Navigation
    nav_overview: 'Áttekintés',
    nav_scripts: 'Script Generátor',
    nav_hooks: 'Hook Könyvtár',
    nav_videos: 'Videó Gyár',
    nav_analytics: 'Analitika',
    nav_notion: 'Notion Analitika',
    nav_settings: 'Beállítások',
    nav_logout: 'Kijelentkezés',
    
    // Auth
    login_title: 'Bejelentkezés',
    register_title: 'Regisztráció',
    email: 'E-mail',
    password: 'Jelszó',
    name: 'Név',
    login_button: 'Bejelentkezés',
    register_button: 'Regisztráció',
    forgot_password: 'Elfelejtett jelszó',
    reset_password: 'Jelszó visszaállítás',
    
    // Dashboard Overview
    welcome: 'Üdvözöl',
    welcome_message: 'Készen állsz piacképes YouTube Shorts-okat készíteni?',
    total_scripts: 'Scriptek',
    total_hooks: 'Hookok',
    avg_retention: 'Retention %',
    swipe_rate: 'Swipe Rate %',
    recent_scripts: 'Legutóbbi Scriptek',
    no_scripts_yet: 'Még nincs script',
    create_first_script: 'Hozd létre az első scriptedet a generátorban',
    quick_actions: 'Gyors Műveletek',
    script_generation: 'Script Generálás',
    script_generation_desc: 'AI-powered német faith scriptek',
    video_creation: 'Videó Készítés',
    video_creation_desc: 'TTS + B-roll + karaoke',
    analytics_upload: 'Analytics Feltöltés',
    analytics_upload_desc: 'CSV import Notion-ből',
    how_to_start: 'Hogyan kezdj neki?',
    how_to_start_desc: 'Kövesd ezeket a lépéseket a sikeres YouTube Shorts készítéséhez',
    step_1_title: 'Generálj AI scripteket',
    step_1_desc: 'Emotional faith-based tartalommal',
    step_2_title: 'Töltsd fel analytics adatokat',
    step_2_desc: 'CSV-ből vagy Notion API-val',
    step_3_title: 'ML-optimalizált generálás',
    step_3_desc: 'Top patterns alapján',
    step_4_title: 'Készíts piacképes videót',
    step_4_desc: 'Teljes video pipeline',
    
    // Script Generator
    script_generator: 'Script Generátor',
    script_generator_subtitle: 'AI-powered német faith-niche YouTube Shorts scriptek',
    settings: 'Beállítások',
    topic: 'Téma',
    topic_placeholder: 'pl. Isten szeretete, Ima ereje, stb.',
    keywords: 'Kulcsszavak',
    add_keyword: 'Kulcsszó hozzáadása',
    mode: 'Mód',
    use_analytics: 'Analitika használata (ML optimalizáció)',
    analytics_disabled: 'Nincs elég analytics adat',
    generate: 'Generálás',
    generating: 'Generálás...',
    generated_script: 'Generált Script',
    hook: 'Hook',
    script: 'Script',
    full_script: 'Teljes Script',
    character_count: 'Karakterszám',
    hook_type: 'Hook Típus',
    generated_with_analytics: 'ML-optimalizált',
    copy: 'Másolás',
    copied: 'Vágólapra másolva!',
    
    // Hook Library
    hook_library: 'Hook Könyvtár',
    hook_library_subtitle: 'Performans-követett hook gyűjtemény',
    search_hooks: 'Hookok keresése...',
    all_modes: 'Minden mód',
    all_types: 'Minden típus',
    sort_by: 'Rendezés',
    sort_created: 'Létrehozás dátuma',
    sort_retention: 'Retention',
    sort_usage: 'Használat',
    create_hook: 'Új Hook',
    hook_text: 'Hook Szöveg',
    retention: 'Retention',
    usage_count: 'Használva',
    tags: 'Címkék',
    delete: 'Törlés',
    add_tag: 'Címke hozzáadása',
    no_hooks_yet: 'Még nincs hook',
    create_first_hook: 'Hozz létre egy új hookot vagy generálj scriptet',
    
    // Video Factory
    video_factory: 'Videó Gyár',
    video_factory_subtitle: 'AI-powered videó generálás: TTS + B-roll + karaoke feliratok',
    select_script: 'Script Kiválasztása',
    select_script_prompt: 'Válassz egy scriptet...',
    voice_settings: 'Hang Beállítások (ElevenLabs)',
    voice_id: 'Voice ID',
    voice_id_placeholder: 'pl. CBPNfSFlxFnoBab9ZbDZ',
    stability: 'Stability',
    similarity_boost: 'Similarity Boost',
    style: 'Style',
    speaker_boost: 'Speaker Boost (ajánlott)',
    video_settings: 'Videó Beállítások',
    broll_search: 'B-roll Keresés (Pexels)',
    broll_placeholder: 'pl. faith, spirituality, peaceful (üres = auto topic)',
    broll_hint: 'Ha üresen hagyod, a script topic-ját használja',
    background_music: 'Háttérzene URL (opcionális)',
    music_placeholder: 'https://example.com/music.mp3',
    music_hint: 'Stock music vagy saját URL (MP3)',
    start_generation: 'Videó Generálás Indítása',
    generation_in_progress: 'Generálás folyamatban...',
    video_pipeline: 'Videó Pipeline',
    generated_videos: 'Generált Videók',
    no_videos_yet: 'Még nincs generált videó',
    select_and_generate: 'Válassz egy scriptet és indítsd el a videó generálást!',
    
    // Analytics
    analytics: 'Analytics Dashboard',
    analytics_subtitle: 'Performance metrikák és insights',
    total_views: 'Összes Megtekintés',
    total_likes: 'Összes Like',
    total_comments: 'Kommentek',
    new_subscribers: 'Új Feliratkozók',
    avg_retention_rate: 'Átlag Retention Rate',
    avg_swipe_rate: 'Átlag Swipe Rate',
    excellent: 'Kiváló',
    improvable: 'Fejleszthető',
    hook_type_performance: 'Hook Típus Performance',
    latest_metrics: 'Legutóbbi Metrikák',
    no_analytics_yet: 'Még nincs analytics adat',
    upload_csv_or_add_metrics: 'Töltsd fel a Notion CSV-t vagy adj hozzá metrics-et',
    
    // Notion Analytics
    notion_analytics: 'Notion Analitika',
    notion_subtitle: 'CSV import/export és ML optimization insights',
    import_csv: 'CSV Importálás',
    export_csv: 'Adatok Exportálása',
    view_guide: 'Algoritmus Guide',
    analytics_insights: 'Analytics Insights',
    imported_rows: 'Importált Sorok',
    top_hooks: 'Top Performans Hookok',
    top_scripts: 'Top Performans Scriptek',
    no_data_yet: 'Még nincs Notion adat',
    import_csv_to_start: 'Importálj CSV-t az ML optimization használatához',
    
    // Settings
    settings_title: 'Beállítások',
    settings_subtitle: 'Profil és API kulcsok kezelése',
    profile: 'Profil',
    api_keys: 'API Kulcsok',
    api_keys_warning: '⚠️ Figyelem: A kulcsok a böngésző localStorage-ban tárolódnak!',
    save_keys: 'Kulcsok Mentése',
    keys_saved: 'API kulcsok mentve!',
    logout: 'Kijelentkezés',
    logout_subtitle: 'Munkamenet befejezése',
    logout_success: 'Sikeresen kijelentkeztél!',
    
    // Common
    save: 'Mentés',
    cancel: 'Mégse',
    close: 'Bezárás',
    edit: 'Szerkesztés',
    loading: 'Betöltés...',
    error: 'Hiba',
    success: 'Siker',
    characters: 'karakter',
    created_at: 'Létrehozva',
    updated_at: 'Frissítve'
  },
  
  de: {
    // Navigation
    nav_overview: 'Übersicht',
    nav_scripts: 'Skript-Generator',
    nav_hooks: 'Hook-Bibliothek',
    nav_videos: 'Video-Fabrik',
    nav_analytics: 'Analytik',
    nav_notion: 'Notion Analytik',
    nav_settings: 'Einstellungen',
    nav_logout: 'Abmelden',
    
    // Auth
    login_title: 'Anmelden',
    register_title: 'Registrieren',
    email: 'E-Mail',
    password: 'Passwort',
    name: 'Name',
    login_button: 'Anmelden',
    register_button: 'Registrieren',
    forgot_password: 'Passwort vergessen',
    reset_password: 'Passwort zurücksetzen',
    
    // Dashboard Overview
    welcome: 'Willkommen',
    welcome_message: 'Bereit, marktfähige YouTube Shorts zu erstellen?',
    total_scripts: 'Skripte',
    total_hooks: 'Hooks',
    avg_retention: 'Retention %',
    swipe_rate: 'Swipe Rate %',
    recent_scripts: 'Neueste Skripte',
    no_scripts_yet: 'Noch keine Skripte',
    create_first_script: 'Erstelle dein erstes Skript im Generator',
    quick_actions: 'Schnellaktionen',
    script_generation: 'Skript-Erstellung',
    script_generation_desc: 'KI-gestützte deutsche Glaubens-Skripte',
    video_creation: 'Video-Erstellung',
    video_creation_desc: 'TTS + B-Roll + Karaoke',
    analytics_upload: 'Analytics-Upload',
    analytics_upload_desc: 'CSV-Import aus Notion',
    how_to_start: 'Wie fange ich an?',
    how_to_start_desc: 'Folge diesen Schritten für erfolgreiche YouTube Shorts',
    step_1_title: 'KI-Skripte generieren',
    step_1_desc: 'Emotionale Glaubens-Inhalte',
    step_2_title: 'Analytics-Daten hochladen',
    step_2_desc: 'Aus CSV oder Notion API',
    step_3_title: 'ML-optimierte Generierung',
    step_3_desc: 'Basierend auf Top-Patterns',
    step_4_title: 'Marktfähiges Video erstellen',
    step_4_desc: 'Vollständige Video-Pipeline',
    
    // Script Generator
    script_generator: 'Skript-Generator',
    script_generator_subtitle: 'KI-gestützte deutsche Glaubens-Nische YouTube Shorts Skripte',
    settings: 'Einstellungen',
    topic: 'Thema',
    topic_placeholder: 'z.B. Gottes Liebe, Kraft des Gebets, usw.',
    keywords: 'Schlüsselwörter',
    add_keyword: 'Schlüsselwort hinzufügen',
    mode: 'Modus',
    use_analytics: 'Analytik verwenden (ML-Optimierung)',
    analytics_disabled: 'Nicht genug Analytik-Daten',
    generate: 'Generieren',
    generating: 'Wird generiert...',
    generated_script: 'Generiertes Skript',
    hook: 'Hook',
    script: 'Skript',
    full_script: 'Vollständiges Skript',
    character_count: 'Zeichenzahl',
    hook_type: 'Hook-Typ',
    generated_with_analytics: 'ML-optimiert',
    copy: 'Kopieren',
    copied: 'In Zwischenablage kopiert!',
    
    // Hook Library
    hook_library: 'Hook-Bibliothek',
    hook_library_subtitle: 'Leistungsverfolgung Hook-Sammlung',
    search_hooks: 'Hooks durchsuchen...',
    all_modes: 'Alle Modi',
    all_types: 'Alle Typen',
    sort_by: 'Sortieren nach',
    sort_created: 'Erstellungsdatum',
    sort_retention: 'Retention',
    sort_usage: 'Verwendung',
    create_hook: 'Neuer Hook',
    hook_text: 'Hook-Text',
    retention: 'Retention',
    usage_count: 'Verwendet',
    tags: 'Tags',
    delete: 'Löschen',
    add_tag: 'Tag hinzufügen',
    no_hooks_yet: 'Noch keine Hooks',
    create_first_hook: 'Erstelle einen neuen Hook oder generiere ein Skript',
    
    // Video Factory
    video_factory: 'Video-Fabrik',
    video_factory_subtitle: 'KI-gestützte Videogenerierung: TTS + B-Roll + Karaoke-Untertitel',
    select_script: 'Skript auswählen',
    select_script_prompt: 'Wähle ein Skript...',
    voice_settings: 'Stimmeneinstellungen (ElevenLabs)',
    voice_id: 'Voice ID',
    voice_id_placeholder: 'z.B. CBPNfSFlxFnoBab9ZbDZ',
    stability: 'Stabilität',
    similarity_boost: 'Ähnlichkeits-Boost',
    style: 'Stil',
    speaker_boost: 'Lautsprecher-Boost (empfohlen)',
    video_settings: 'Video-Einstellungen',
    broll_search: 'B-Roll-Suche (Pexels)',
    broll_placeholder: 'z.B. Glaube, Spiritualität, friedlich (leer = Auto-Thema)',
    broll_hint: 'Wenn leer, wird das Skript-Thema verwendet',
    background_music: 'Hintergrundmusik URL (optional)',
    music_placeholder: 'https://example.com/music.mp3',
    music_hint: 'Stock-Musik oder eigene URL (MP3)',
    start_generation: 'Videogenerierung starten',
    generation_in_progress: 'Generierung läuft...',
    video_pipeline: 'Video-Pipeline',
    generated_videos: 'Generierte Videos',
    no_videos_yet: 'Noch keine generierten Videos',
    select_and_generate: 'Wähle ein Skript und starte die Videogenerierung!',
    
    // Analytics
    analytics: 'Analytics-Dashboard',
    analytics_subtitle: 'Leistungsmetriken und Einblicke',
    total_views: 'Gesamtansichten',
    total_likes: 'Gesamte Likes',
    total_comments: 'Kommentare',
    new_subscribers: 'Neue Abonnenten',
    avg_retention_rate: 'Durchschn. Retention-Rate',
    avg_swipe_rate: 'Durchschn. Swipe-Rate',
    excellent: 'Ausgezeichnet',
    improvable: 'Verbesserbar',
    hook_type_performance: 'Hook-Typ-Leistung',
    latest_metrics: 'Neueste Metriken',
    no_analytics_yet: 'Noch keine Analytik-Daten',
    upload_csv_or_add_metrics: 'Lade die Notion CSV hoch oder füge Metriken hinzu',
    
    // Notion Analytics
    notion_analytics: 'Notion Analytik',
    notion_subtitle: 'CSV-Import/Export und ML-Optimierungs-Einblicke',
    import_csv: 'CSV importieren',
    export_csv: 'Daten exportieren',
    view_guide: 'Algorithmus-Leitfaden',
    analytics_insights: 'Analytik-Einblicke',
    imported_rows: 'Importierte Zeilen',
    top_hooks: 'Top-Leistungs-Hooks',
    top_scripts: 'Top-Leistungs-Skripte',
    no_data_yet: 'Noch keine Notion-Daten',
    import_csv_to_start: 'Importiere CSV für ML-Optimierung',
    
    // Settings
    settings_title: 'Einstellungen',
    settings_subtitle: 'Profil- und API-Schlüsselverwaltung',
    profile: 'Profil',
    api_keys: 'API-Schlüssel',
    api_keys_warning: '⚠️ Achtung: Schlüssel werden im Browser-localStorage gespeichert!',
    save_keys: 'Schlüssel speichern',
    keys_saved: 'API-Schlüssel gespeichert!',
    logout: 'Abmelden',
    logout_subtitle: 'Sitzung beenden',
    logout_success: 'Erfolgreich abgemeldet!',
    
    // Common
    save: 'Speichern',
    cancel: 'Abbrechen',
    close: 'Schließen',
    edit: 'Bearbeiten',
    loading: 'Laden...',
    error: 'Fehler',
    success: 'Erfolg',
    characters: 'Zeichen',
    created_at: 'Erstellt',
    updated_at: 'Aktualisiert'
  },
  
  en: {
    // Navigation
    nav_overview: 'Overview',
    nav_scripts: 'Script Generator',
    nav_hooks: 'Hook Library',
    nav_videos: 'Video Factory',
    nav_analytics: 'Analytics',
    nav_notion: 'Notion Analytics',
    nav_settings: 'Settings',
    nav_logout: 'Logout',
    
    // Auth
    login_title: 'Login',
    register_title: 'Register',
    email: 'Email',
    password: 'Password',
    name: 'Name',
    login_button: 'Login',
    register_button: 'Register',
    forgot_password: 'Forgot Password',
    reset_password: 'Reset Password',
    
    // Dashboard Overview
    welcome: 'Welcome',
    welcome_message: 'Ready to create market-ready YouTube Shorts?',
    total_scripts: 'Scripts',
    total_hooks: 'Hooks',
    avg_retention: 'Retention %',
    swipe_rate: 'Swipe Rate %',
    recent_scripts: 'Recent Scripts',
    no_scripts_yet: 'No scripts yet',
    create_first_script: 'Create your first script in the generator',
    quick_actions: 'Quick Actions',
    script_generation: 'Script Generation',
    script_generation_desc: 'AI-powered German faith scripts',
    video_creation: 'Video Creation',
    video_creation_desc: 'TTS + B-roll + karaoke',
    analytics_upload: 'Analytics Upload',
    analytics_upload_desc: 'CSV import from Notion',
    how_to_start: 'How to Start?',
    how_to_start_desc: 'Follow these steps for successful YouTube Shorts',
    step_1_title: 'Generate AI scripts',
    step_1_desc: 'Emotional faith-based content',
    step_2_title: 'Upload analytics data',
    step_2_desc: 'From CSV or Notion API',
    step_3_title: 'ML-optimized generation',
    step_3_desc: 'Based on top patterns',
    step_4_title: 'Create market-ready video',
    step_4_desc: 'Complete video pipeline',
    
    // Script Generator
    script_generator: 'Script Generator',
    script_generator_subtitle: 'AI-powered German faith-niche YouTube Shorts scripts',
    settings: 'Settings',
    topic: 'Topic',
    topic_placeholder: 'e.g. God\'s love, Power of prayer, etc.',
    keywords: 'Keywords',
    add_keyword: 'Add Keyword',
    mode: 'Mode',
    use_analytics: 'Use Analytics (ML optimization)',
    analytics_disabled: 'Not enough analytics data',
    generate: 'Generate',
    generating: 'Generating...',
    generated_script: 'Generated Script',
    hook: 'Hook',
    script: 'Script',
    full_script: 'Full Script',
    character_count: 'Character Count',
    hook_type: 'Hook Type',
    generated_with_analytics: 'ML-optimized',
    copy: 'Copy',
    copied: 'Copied to clipboard!',
    
    // Hook Library
    hook_library: 'Hook Library',
    hook_library_subtitle: 'Performance-tracked hook collection',
    search_hooks: 'Search hooks...',
    all_modes: 'All Modes',
    all_types: 'All Types',
    sort_by: 'Sort By',
    sort_created: 'Created Date',
    sort_retention: 'Retention',
    sort_usage: 'Usage',
    create_hook: 'New Hook',
    hook_text: 'Hook Text',
    retention: 'Retention',
    usage_count: 'Used',
    tags: 'Tags',
    delete: 'Delete',
    add_tag: 'Add Tag',
    no_hooks_yet: 'No hooks yet',
    create_first_hook: 'Create a new hook or generate a script',
    
    // Video Factory
    video_factory: 'Video Factory',
    video_factory_subtitle: 'AI-powered video generation: TTS + B-roll + karaoke captions',
    select_script: 'Select Script',
    select_script_prompt: 'Choose a script...',
    voice_settings: 'Voice Settings (ElevenLabs)',
    voice_id: 'Voice ID',
    voice_id_placeholder: 'e.g. CBPNfSFlxFnoBab9ZbDZ',
    stability: 'Stability',
    similarity_boost: 'Similarity Boost',
    style: 'Style',
    speaker_boost: 'Speaker Boost (recommended)',
    video_settings: 'Video Settings',
    broll_search: 'B-roll Search (Pexels)',
    broll_placeholder: 'e.g. faith, spirituality, peaceful (empty = auto topic)',
    broll_hint: 'If empty, uses script topic',
    background_music: 'Background Music URL (optional)',
    music_placeholder: 'https://example.com/music.mp3',
    music_hint: 'Stock music or custom URL (MP3)',
    start_generation: 'Start Video Generation',
    generation_in_progress: 'Generation in progress...',
    video_pipeline: 'Video Pipeline',
    generated_videos: 'Generated Videos',
    no_videos_yet: 'No generated videos yet',
    select_and_generate: 'Select a script and start video generation!',
    
    // Analytics
    analytics: 'Analytics Dashboard',
    analytics_subtitle: 'Performance metrics and insights',
    total_views: 'Total Views',
    total_likes: 'Total Likes',
    total_comments: 'Comments',
    new_subscribers: 'New Subscribers',
    avg_retention_rate: 'Avg Retention Rate',
    avg_swipe_rate: 'Avg Swipe Rate',
    excellent: 'Excellent',
    improvable: 'Improvable',
    hook_type_performance: 'Hook Type Performance',
    latest_metrics: 'Latest Metrics',
    no_analytics_yet: 'No analytics data yet',
    upload_csv_or_add_metrics: 'Upload Notion CSV or add metrics',
    
    // Notion Analytics
    notion_analytics: 'Notion Analytics',
    notion_subtitle: 'CSV import/export and ML optimization insights',
    import_csv: 'Import CSV',
    export_csv: 'Export Data',
    view_guide: 'Algorithm Guide',
    analytics_insights: 'Analytics Insights',
    imported_rows: 'Imported Rows',
    top_hooks: 'Top Performance Hooks',
    top_scripts: 'Top Performance Scripts',
    no_data_yet: 'No Notion data yet',
    import_csv_to_start: 'Import CSV to use ML optimization',
    
    // Settings
    settings_title: 'Settings',
    settings_subtitle: 'Profile and API key management',
    profile: 'Profile',
    api_keys: 'API Keys',
    api_keys_warning: '⚠️ Warning: Keys are stored in browser localStorage!',
    save_keys: 'Save Keys',
    keys_saved: 'API keys saved!',
    logout: 'Logout',
    logout_subtitle: 'End session',
    logout_success: 'Successfully logged out!',
    
    // Common
    save: 'Save',
    cancel: 'Cancel',
    close: 'Close',
    edit: 'Edit',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    characters: 'characters',
    created_at: 'Created',
    updated_at: 'Updated'
  },
  
  pl: {
    // Navigation
    nav_overview: 'Przegląd',
    nav_scripts: 'Generator Skryptów',
    nav_hooks: 'Biblioteka Hooków',
    nav_videos: 'Fabryka Wideo',
    nav_analytics: 'Analityka',
    nav_notion: 'Analityka Notion',
    nav_settings: 'Ustawienia',
    nav_logout: 'Wyloguj',
    
    // Auth
    login_title: 'Zaloguj',
    register_title: 'Zarejestruj',
    email: 'E-mail',
    password: 'Hasło',
    name: 'Imię',
    login_button: 'Zaloguj',
    register_button: 'Zarejestruj',
    forgot_password: 'Zapomniałeś hasła',
    reset_password: 'Resetuj hasło',
    
    // Dashboard Overview
    welcome: 'Witaj',
    total_scripts: 'Wszystkie Skrypty',
    total_hooks: 'Wszystkie Hooki',
    avg_retention: 'Śr. Retention',
    recent_scripts: 'Ostatnie Skrypty',
    no_scripts_yet: 'Brak skryptów',
    create_first_script: 'Utwórz swój pierwszy skrypt w generatorze',
    
    // Script Generator
    script_generator: 'Generator Skryptów',
    script_generator_subtitle: 'Skrypty YouTube Shorts z AI (niemiecka nisza religijna)',
    settings: 'Ustawienia',
    topic: 'Temat',
    topic_placeholder: 'np. Miłość Boga, Moc modlitwy, itp.',
    keywords: 'Słowa kluczowe',
    add_keyword: 'Dodaj słowo kluczowe',
    mode: 'Tryb',
    use_analytics: 'Użyj analityki (optymalizacja ML)',
    analytics_disabled: 'Za mało danych analitycznych',
    generate: 'Generuj',
    generating: 'Generowanie...',
    generated_script: 'Wygenerowany Skrypt',
    hook: 'Hook',
    script: 'Skrypt',
    full_script: 'Pełny Skrypt',
    character_count: 'Liczba znaków',
    hook_type: 'Typ Hooka',
    generated_with_analytics: 'Zoptymalizowany ML',
    copy: 'Kopiuj',
    copied: 'Skopiowano do schowka!',
    
    // Hook Library
    hook_library: 'Biblioteka Hooków',
    hook_library_subtitle: 'Kolekcja hooków z śledzeniem wydajności',
    search_hooks: 'Szukaj hooków...',
    all_modes: 'Wszystkie tryby',
    all_types: 'Wszystkie typy',
    sort_by: 'Sortuj według',
    sort_created: 'Data utworzenia',
    sort_retention: 'Retention',
    sort_usage: 'Użycie',
    create_hook: 'Nowy Hook',
    hook_text: 'Tekst Hooka',
    retention: 'Retention',
    usage_count: 'Użyty',
    tags: 'Tagi',
    delete: 'Usuń',
    add_tag: 'Dodaj tag',
    no_hooks_yet: 'Brak hooków',
    create_first_hook: 'Utwórz nowy hook lub wygeneruj skrypt',
    
    // Video Factory
    video_factory: 'Fabryka Wideo',
    video_factory_subtitle: 'Generowanie wideo z AI: TTS + B-roll + napisy karaoke',
    select_script: 'Wybierz Skrypt',
    select_script_prompt: 'Wybierz skrypt...',
    voice_settings: 'Ustawienia Głosu (ElevenLabs)',
    voice_id: 'Voice ID',
    voice_id_placeholder: 'np. CBPNfSFlxFnoBab9ZbDZ',
    stability: 'Stabilność',
    similarity_boost: 'Boost Podobieństwa',
    style: 'Styl',
    speaker_boost: 'Boost Głośnika (zalecane)',
    video_settings: 'Ustawienia Wideo',
    broll_search: 'Wyszukiwanie B-roll (Pexels)',
    broll_placeholder: 'np. wiara, duchowość, spokój (puste = auto temat)',
    broll_hint: 'Jeśli puste, użyje tematu skryptu',
    background_music: 'URL Muzyki Tła (opcjonalne)',
    music_placeholder: 'https://example.com/music.mp3',
    music_hint: 'Muzyka stockowa lub własny URL (MP3)',
    start_generation: 'Rozpocznij Generowanie Wideo',
    generation_in_progress: 'Generowanie w toku...',
    video_pipeline: 'Pipeline Wideo',
    generated_videos: 'Wygenerowane Wideo',
    no_videos_yet: 'Brak wygenerowanych wideo',
    select_and_generate: 'Wybierz skrypt i rozpocznij generowanie wideo!',
    
    // Analytics
    analytics: 'Panel Analityki',
    analytics_subtitle: 'Metryki wydajności i spostrzeżenia',
    total_views: 'Wszystkie Wyświetlenia',
    total_likes: 'Wszystkie Polubienia',
    total_comments: 'Komentarze',
    new_subscribers: 'Nowi Subskrybenci',
    avg_retention_rate: 'Śr. Wskaźnik Retention',
    avg_swipe_rate: 'Śr. Wskaźnik Swipe',
    excellent: 'Doskonały',
    improvable: 'Do poprawy',
    hook_type_performance: 'Wydajność Typu Hooka',
    latest_metrics: 'Najnowsze Metryki',
    no_analytics_yet: 'Brak danych analitycznych',
    upload_csv_or_add_metrics: 'Prześlij CSV z Notion lub dodaj metryki',
    
    // Notion Analytics
    notion_analytics: 'Analityka Notion',
    notion_subtitle: 'Import/export CSV i optymalizacja ML',
    import_csv: 'Importuj CSV',
    export_csv: 'Eksportuj Dane',
    view_guide: 'Przewodnik Algorytmu',
    analytics_insights: 'Spostrzeżenia Analityki',
    imported_rows: 'Zaimportowane Wiersze',
    top_hooks: 'Top Hooki Wydajności',
    top_scripts: 'Top Skrypty Wydajności',
    no_data_yet: 'Brak danych Notion',
    import_csv_to_start: 'Importuj CSV do optymalizacji ML',
    
    // Settings
    settings_title: 'Ustawienia',
    settings_subtitle: 'Zarządzanie profilem i kluczami API',
    profile: 'Profil',
    api_keys: 'Klucze API',
    api_keys_warning: '⚠️ Uwaga: Klucze są przechowywane w localStorage przeglądarki!',
    save_keys: 'Zapisz Klucze',
    keys_saved: 'Klucze API zapisane!',
    logout: 'Wyloguj',
    logout_subtitle: 'Zakończ sesję',
    logout_success: 'Pomyślnie wylogowano!',
    
    // Common
    save: 'Zapisz',
    cancel: 'Anuluj',
    close: 'Zamknij',
    edit: 'Edytuj',
    loading: 'Ładowanie...',
    error: 'Błąd',
    success: 'Sukces',
    characters: 'znaków',
    created_at: 'Utworzono',
    updated_at: 'Zaktualizowano'
  },
  
  nl: {
    // Navigation
    nav_overview: 'Overzicht',
    nav_scripts: 'Script Generator',
    nav_hooks: 'Hook Bibliotheek',
    nav_videos: 'Video Fabriek',
    nav_analytics: 'Analytics',
    nav_notion: 'Notion Analytics',
    nav_settings: 'Instellingen',
    nav_logout: 'Uitloggen',
    
    // Auth
    login_title: 'Inloggen',
    register_title: 'Registreren',
    email: 'E-mail',
    password: 'Wachtwoord',
    name: 'Naam',
    login_button: 'Inloggen',
    register_button: 'Registreren',
    forgot_password: 'Wachtwoord vergeten',
    reset_password: 'Wachtwoord resetten',
    
    // Dashboard Overview
    welcome: 'Welkom',
    total_scripts: 'Totaal Scripts',
    total_hooks: 'Totaal Hooks',
    avg_retention: 'Gem. Retention',
    recent_scripts: 'Recente Scripts',
    no_scripts_yet: 'Nog geen scripts',
    create_first_script: 'Maak je eerste script in de generator',
    
    // Script Generator
    script_generator: 'Script Generator',
    script_generator_subtitle: 'AI-aangedreven Duitse geloof-niche YouTube Shorts scripts',
    settings: 'Instellingen',
    topic: 'Onderwerp',
    topic_placeholder: 'bijv. Gods liefde, Kracht van gebed, enz.',
    keywords: 'Trefwoorden',
    add_keyword: 'Trefwoord toevoegen',
    mode: 'Modus',
    use_analytics: 'Analytics gebruiken (ML-optimalisatie)',
    analytics_disabled: 'Niet genoeg analytics data',
    generate: 'Genereren',
    generating: 'Genereren...',
    generated_script: 'Gegenereerd Script',
    hook: 'Hook',
    script: 'Script',
    full_script: 'Volledig Script',
    character_count: 'Aantal tekens',
    hook_type: 'Hook Type',
    generated_with_analytics: 'ML-geoptimaliseerd',
    copy: 'Kopiëren',
    copied: 'Gekopieerd naar klembord!',
    
    // Hook Library
    hook_library: 'Hook Bibliotheek',
    hook_library_subtitle: 'Prestatie-getrackte hook collectie',
    search_hooks: 'Hooks zoeken...',
    all_modes: 'Alle Modi',
    all_types: 'Alle Types',
    sort_by: 'Sorteren op',
    sort_created: 'Aanmaakdatum',
    sort_retention: 'Retention',
    sort_usage: 'Gebruik',
    create_hook: 'Nieuwe Hook',
    hook_text: 'Hook Tekst',
    retention: 'Retention',
    usage_count: 'Gebruikt',
    tags: 'Tags',
    delete: 'Verwijderen',
    add_tag: 'Tag toevoegen',
    no_hooks_yet: 'Nog geen hooks',
    create_first_hook: 'Maak een nieuwe hook of genereer een script',
    
    // Video Factory
    video_factory: 'Video Fabriek',
    video_factory_subtitle: 'AI-aangedreven videogeneratie: TTS + B-roll + karaoke ondertiteling',
    select_script: 'Selecteer Script',
    select_script_prompt: 'Kies een script...',
    voice_settings: 'Stem Instellingen (ElevenLabs)',
    voice_id: 'Voice ID',
    voice_id_placeholder: 'bijv. CBPNfSFlxFnoBab9ZbDZ',
    stability: 'Stabiliteit',
    similarity_boost: 'Gelijkenis Boost',
    style: 'Stijl',
    speaker_boost: 'Speaker Boost (aanbevolen)',
    video_settings: 'Video Instellingen',
    broll_search: 'B-roll Zoeken (Pexels)',
    broll_placeholder: 'bijv. geloof, spiritualiteit, rustig (leeg = auto onderwerp)',
    broll_hint: 'Als leeg, gebruikt script onderwerp',
    background_music: 'Achtergrondmuziek URL (optioneel)',
    music_placeholder: 'https://example.com/music.mp3',
    music_hint: 'Stock muziek of eigen URL (MP3)',
    start_generation: 'Start Video Generatie',
    generation_in_progress: 'Generatie bezig...',
    video_pipeline: 'Video Pipeline',
    generated_videos: 'Gegenereerde Videos',
    no_videos_yet: 'Nog geen gegenereerde videos',
    select_and_generate: 'Selecteer een script en start videogeneratie!',
    
    // Analytics
    analytics: 'Analytics Dashboard',
    analytics_subtitle: 'Prestatiemetrieken en inzichten',
    total_views: 'Totaal Weergaven',
    total_likes: 'Totaal Likes',
    total_comments: 'Reacties',
    new_subscribers: 'Nieuwe Abonnees',
    avg_retention_rate: 'Gem. Retention Rate',
    avg_swipe_rate: 'Gem. Swipe Rate',
    excellent: 'Uitstekend',
    improvable: 'Verbeterbaar',
    hook_type_performance: 'Hook Type Prestatie',
    latest_metrics: 'Laatste Metrieken',
    no_analytics_yet: 'Nog geen analytics data',
    upload_csv_or_add_metrics: 'Upload Notion CSV of voeg metrieken toe',
    
    // Notion Analytics
    notion_analytics: 'Notion Analytics',
    notion_subtitle: 'CSV import/export en ML-optimalisatie inzichten',
    import_csv: 'CSV Importeren',
    export_csv: 'Data Exporteren',
    view_guide: 'Algoritme Gids',
    analytics_insights: 'Analytics Inzichten',
    imported_rows: 'Geïmporteerde Rijen',
    top_hooks: 'Top Prestatie Hooks',
    top_scripts: 'Top Prestatie Scripts',
    no_data_yet: 'Nog geen Notion data',
    import_csv_to_start: 'Importeer CSV voor ML-optimalisatie',
    
    // Settings
    settings_title: 'Instellingen',
    settings_subtitle: 'Profiel en API sleutelbeheer',
    profile: 'Profiel',
    api_keys: 'API Sleutels',
    api_keys_warning: '⚠️ Waarschuwing: Sleutels worden opgeslagen in browser localStorage!',
    save_keys: 'Sleutels Opslaan',
    keys_saved: 'API sleutels opgeslagen!',
    logout: 'Uitloggen',
    logout_subtitle: 'Sessie beëindigen',
    logout_success: 'Succesvol uitgelogd!',
    
    // Common
    save: 'Opslaan',
    cancel: 'Annuleren',
    close: 'Sluiten',
    edit: 'Bewerken',
    loading: 'Laden...',
    error: 'Fout',
    success: 'Succes',
    characters: 'tekens',
    created_at: 'Aangemaakt',
    updated_at: 'Bijgewerkt'
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(
    localStorage.getItem('language') || 'hu'
  );

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key) => {
    // Map 'us' to 'en' for backwards compatibility
    const langCode = language === 'us' ? 'en' : language;
    return translations[langCode]?.[key] || translations['hu'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};
